export const categories: string[] = [
  "Vehículos",
  "Inmuebles",
  "Supermercado",
  "Tecnología",
  "Hogar y muebles",
  "Electrodomésticos",
  "Herramientas",
  "Construcción",
  "Desportes y fitnes",
  "Accesorios para vehículos",
  "Moda",
  "Juegos y jueguetes",
  "Bebés",
  "Beleza y cuidado personal",
  "Salud y equipamento médico",
  "Industrias y oficinas",
  "Agro",
  "Productos sustentables",
  "Servicios",
  "Mas vendidos",
  "Tiendas oficiales",
  "Ver más categorías",
];
